CC=arm-none-eabi-gcc
MACH=cortex-m4
CFLAGS= -c -mcpu=$(MACH) -mthumb -mfloat-abi=soft -std=gnu11 -Wall -O0
LDFLAGS= -mcpu=$(MACH) -mthumb -mfloat-abi=soft --specs=nano.specs -T stm32_ls.ld -Wl,-Map=final.map
LDFLAGS_SH= -mcpu=$(MACH) -mthumb -mfloat-abi=soft --specs=rdimon.specs -T stm32_ls.ld -Wl,-Map=final.map

all:main.o startup_code.o

semi:main.o startup_code.o

main.o: Emain.c
	$(CC) $(CFLAGS) -o $@ $^

startup_code.o:startup_code.c
	$(CC) $(CFLAGS) -o $@ $^

load:

	openocd -f board/stm32f4discovery.cfg 